
		; Skidmarks/Guardian disk imager
		;
		; Written by JOTD
		;
		; Sector format description:
		;
		; sync ($4489)

		; disk structure is reversed. Reverting the dump of tracks
		; allow to rip files fully
		;
		; when reversed, track 0 (was track 159) contains the header
		;
		; 0.L: fourcc id (ex: 'GARD')
		; 4.W: number of files on disk
		; 12.L: fourcc filename + file info (on 40 bytes each)
		; 
		; 00: 47 41 52 44: GARD
		; 04: 00 17: nb files
		;     00 00 00 90 14 50: crap
		; 12: 69 6E 66 6F: info
		; looks like bull bulk fill
		; 00 00 00 01 00 00 00 02 00 00 00 03 00 00 00 04
		; 00 00 00 05 00 00 00 06 00 00 00 07
		; 44: 00 00 04 E4: $4E4 size in bytes
		; 48: 00 01: 1.W side?
		; 50: 00 00: 0.W track ?
		
		incdir	Include:
		include	RawDIC.i

		IFD		BARFLY
		OUTPUT	"Guardian.islave"

		IFND	.passchk
		DOSCMD	"WDate  >T:date"
.passchk
		ENDC
		ENDC
		
		SLAVE_HEADER
		dc.b	1	; Slave version
		dc.b	0	; Slave flags
		dc.l	DSK_1	; Pointer to the first disk structure
		dc.l	Text	; Pointer to the text displayed in the imager window

		dc.b	"$VER:"
Text		dc.b	"Guardian imager 1.0",10
		dc.b	"by JOTD on "
		IFD	BARFLY
		INCBIN	"T:date"
		ENDC
	IFD	DATETIME
		incbin	datetime
	ENDC
		dc.b	0
		cnop	0,4

DSK_1		dc.l	0		; Pointer to next disk structure
		dc.w	1		; Disk structure version
		dc.w	DFLG_NORESTRICTIONS		; Disk flags
		dc.l	TL_1		; List of tracks which contain data
		dc.l	0		; UNUSED, ALWAYS SET TO 0!
		dc.l	tracks_0	; List of files to be saved
		dc.l	0		; Table of certain tracks with CRC values
		dc.l	0		; Alternative disk structure, if CRC failed
		dc.l	0		; Called before a disk is read
		dc.l	0		; Called after a disk has been read

TRACK_LENGTH = $1800

DEFTRACK:MACRO
	TLENTRY	\1,\1,TRACK_LENGTH,SYNC_STD,DMFM_Skidmarks
	ENDM
	; generated by a python script (disk_map.py, in sources) 
	; that directly creates proper
	; filenames and value. Much easier than a dynamic decoding
	; and anyway there's only 1 version of that game so...
tracks_0:
	FLENTRY	fn_info,$1800,$4e4
	FLENTRY	fn_sp01,$1ce8,$dfd0
	FLENTRY	fn_da01,$fcb8,$6100
	FLENTRY	fn_sp02,$15db8,$a206
	FLENTRY	fn_da02,$1ffc0,$6100
	FLENTRY	fn_sp03,$260c0,$dd8a
	FLENTRY	fn_da03,$33e50,$6100
	FLENTRY	fn_sp04,$39f50,$106b8
	FLENTRY	fn_da04,$4a608,$6100
	FLENTRY	fn_sp05,$50708,$11be8
	FLENTRY	fn_da05,$622f0,$6100
	FLENTRY	fn_sp06,$683f0,$dfa6
	FLENTRY	fn_da06,$76398,$6100
	FLENTRY	fn_sp07,$7c498,$1036a
	FLENTRY	fn_da07,$8c808,$6100
	FLENTRY	fn_sp08,$92908,$b504
	FLENTRY	fn_da08,$9de10,$6100
	FLENTRY	fn_sp09,$a3f10,$ef4c
	FLENTRY	fn_da09,$b2e60,$6100
	FLENTRY	fn_sp10,$b8f60,$c35e
	FLENTRY	fn_da10,$c52c0,$6100
	FLENTRY	fn_sp11,$cb3c0,$7f8a
	FLENTRY	fn_da11,$d3350,$6100
	FLEND

fn_info:
	dc.b	"info",0
fn_sp01:
	dc.b	"sp01",0
fn_da01:
	dc.b	"da01",0
fn_sp02:
	dc.b	"sp02",0
fn_da02:
	dc.b	"da02",0
fn_sp03:
	dc.b	"sp03",0
fn_da03:
	dc.b	"da03",0
fn_sp04:
	dc.b	"sp04",0
fn_da04:
	dc.b	"da04",0
fn_sp05:
	dc.b	"sp05",0
fn_da05:
	dc.b	"da05",0
fn_sp06:
	dc.b	"sp06",0
fn_da06:
	dc.b	"da06",0
fn_sp07:
	dc.b	"sp07",0
fn_da07:
	dc.b	"da07",0
fn_sp08:
	dc.b	"sp08",0
fn_da08:
	dc.b	"da08",0
fn_sp09:
	dc.b	"sp09",0
fn_da09:
	dc.b	"da09",0
fn_sp10:
	dc.b	"sp10",0
fn_da10:
	dc.b	"da10",0
fn_sp11:
	dc.b	"sp11",0
fn_da11:
	dc.b	"da11",0
	even
TL_1
	DEFTRACK	159
	DEFTRACK	158
	DEFTRACK	157
	DEFTRACK	156
	DEFTRACK	155
	DEFTRACK	154
	DEFTRACK	153
	DEFTRACK	152
	DEFTRACK	151
	DEFTRACK	150
	DEFTRACK	149
	DEFTRACK	148
	DEFTRACK	147
	DEFTRACK	146
	DEFTRACK	145
	DEFTRACK	144
	DEFTRACK	143
	DEFTRACK	142
	DEFTRACK	141
	DEFTRACK	140
	DEFTRACK	139
	DEFTRACK	138
	DEFTRACK	137
	DEFTRACK	136
	DEFTRACK	135
	DEFTRACK	134
	DEFTRACK	133
	DEFTRACK	132
	DEFTRACK	131
	DEFTRACK	130
	DEFTRACK	129
	DEFTRACK	128
	DEFTRACK	127
	DEFTRACK	126
	DEFTRACK	125
	DEFTRACK	124
	DEFTRACK	123
	DEFTRACK	122
	DEFTRACK	121
	DEFTRACK	120
	DEFTRACK	119
	DEFTRACK	118
	DEFTRACK	117
	DEFTRACK	116
	DEFTRACK	115
	DEFTRACK	114
	DEFTRACK	113
	DEFTRACK	112
	DEFTRACK	111
	DEFTRACK	110
	DEFTRACK	109
	DEFTRACK	108
	DEFTRACK	107
	DEFTRACK	106
	DEFTRACK	105
	DEFTRACK	104
	DEFTRACK	103
	DEFTRACK	102
	DEFTRACK	101
	DEFTRACK	100
	DEFTRACK	99
	DEFTRACK	98
	DEFTRACK	97
	DEFTRACK	96
	DEFTRACK	95
	DEFTRACK	94
	DEFTRACK	93
	DEFTRACK	92
	DEFTRACK	91
	DEFTRACK	90
	DEFTRACK	89
	DEFTRACK	88
	DEFTRACK	87
	DEFTRACK	86
	DEFTRACK	85
	DEFTRACK	84
	DEFTRACK	83
	DEFTRACK	82
	DEFTRACK	81
	DEFTRACK	80
	DEFTRACK	79
	DEFTRACK	78
	DEFTRACK	77
	DEFTRACK	76
	DEFTRACK	75
	DEFTRACK	74
	DEFTRACK	73
	DEFTRACK	72
	DEFTRACK	71
	DEFTRACK	70
	DEFTRACK	69
	DEFTRACK	68
	DEFTRACK	67
	DEFTRACK	66
	DEFTRACK	65
	DEFTRACK	64
	DEFTRACK	63
	DEFTRACK	62
	DEFTRACK	61
	DEFTRACK	60
	DEFTRACK	59
	DEFTRACK	58
	DEFTRACK	57
	DEFTRACK	56
	DEFTRACK	55
	DEFTRACK	54
	DEFTRACK	53
	DEFTRACK	52
	DEFTRACK	51
	DEFTRACK	50
	DEFTRACK	49
	DEFTRACK	48
	DEFTRACK	47
	DEFTRACK	46
	DEFTRACK	45
	DEFTRACK	44
	DEFTRACK	43
	DEFTRACK	42
	DEFTRACK	41
	DEFTRACK	40
	DEFTRACK	39
	DEFTRACK	38
	DEFTRACK	37
	DEFTRACK	36
	DEFTRACK	35
	DEFTRACK	34
	DEFTRACK	33
	DEFTRACK	32
	DEFTRACK	31
	DEFTRACK	30
	DEFTRACK	29
	DEFTRACK	28
	DEFTRACK	27
	DEFTRACK	26
	DEFTRACK	25
	DEFTRACK	24
	DEFTRACK	23
	DEFTRACK	22
	DEFTRACK	21
	DEFTRACK	20
	DEFTRACK	19
	DEFTRACK	18
	DEFTRACK	17
	DEFTRACK	16
	DEFTRACK	15
	DEFTRACK	14
	DEFTRACK	13
	DEFTRACK	12
	DEFTRACK	11
	DEFTRACK	10
	DEFTRACK	9
	DEFTRACK	8
	DEFTRACK	7
	DEFTRACK	6
	DEFTRACK	5
	DEFTRACK	4
	DEFTRACK	3
	DEFTRACK	2
	DEFTRACK	1

		TLEND

;======================================================================

DMFM_Skidmarks
	MOVEA.L	A0,A2			; MFM data
	MOVEA.L	A1,A3			; destination

	move.l	A3,A0

	move.l	A2,A1

	addq.l	#2,A1
	LEA	$1808(A1),A2
	MOVE.L	#$55555555,D2
	MOVE.W	#$05FF,D3
.LB_1498
	bsr	.decode
	MOVE.L	D0,(A0)+
	DBF	D3,.LB_1498
	
	bsr	.decode	
	bsr	.decode	
	move.l	d0,d5	; d5: expected track checksum

	MOVE.L	A3,A0
	CLR.L	D0
	MOVE.W	#$05FF,D3
.LB_14BC
	MOVE.L	(A0)+,D4
	ADDX.L	D4,D0
	DBF	D3,.LB_14BC

	MOVE.L	#$FFFFFFFF,D1
	SUB.L	D0,D1

	MOVEQ	#$00,D0
	CMP.L	D5,D1
	BNE.B	_ChecksumError
	RTS	

.decode
	MOVE.L	(A1)+,D0
	AND.L	D2,D0
	ADD.L	D0,D0
	MOVE.L	(A2)+,D1
	AND.L	D2,D1
	OR.L	D1,D0
	rts

_OK		moveq	#IERR_OK,d0
		rts

_ChecksumError	moveq	#IERR_CHECKSUM,d0
		rts

_NoSector	moveq	#IERR_NOSECTOR,d0
		rts
