                   MANHUNTER IN SAN FRANCISCO SOLUTION


DAY ONE
   APART FROM THE ACTIONS AT THE SCENE OF THE CRASH,THE VARIOUS PLACES
   CAN BE VISITED IN ANY ORDER.

   GO LEFT TO BODY
   GET ID CARD (NOTE NAME PETER BROWN)
   GET `MAD' MACHINE
   LOOK AT `MAD'.TRACK TARGETS TO: BANK OF CANTON
                                   WAREHOUSE
                                   FERRY BUILDING
                                   EMBARCADERO FOUNTAIN
                                   HYDE ST PIER
   ENTER "PETER BROWN" IN `MAD' FOR MANHUNTERS APARTMENT

BANK OF CANTON
   ENTER DOOR ON LEFT,GO DOWN TO THE ROOM
   GET NEWSPAPER (NOTE NAME NOAH G)
   SEE HAND
   SEE HEAD
   GET DRAGON NOTE (ON DESK)
   STUDY DOOR (BAT VOMIT INSIDE.WILL READ "TAD TIMOV" OUTSIDE!)
   USE MAD,ENTER NAME "TAD TIMOV" (GIVES HIS APPARTMENT)
   OUTSIDE BANK,GO TO LEFT TO A BODY
   SEE HAND
   SEE HEAD
   GET LAUNDRY TICKET
   GET FANG FROM NECK

WAREHOUSE
   IGNORE THE BIRD
   ENTER WAREHOUSE.ARCADE GAME TO ROOM BOTTOM LEFT
   IN ROOM:-
   GET MALLET (NOTE FISH SHAPE)
   NOTE WALL SIGN
   SEE MESSAGE ON DESK (NOTE THE NAMES-IT`S ADDRESSED TO ZAC,CALLS MIC
   A TRAITOR.

EMBARCADO FOUNTAIN
   ENTER POOL
   ARCADE GAME IN TUNNEL
   ARCADE GAME PAST BATS & RATS
   INTO ROOM
   NOTE MESSAGE
   SEE BODY
   GET EMPTY FLASK
   GET DRIVERS LICENCE (UNDER MATTRESS)
   NOTE NAME "STONE"
   (LICENCE DROPPED BY TRAITOR MIC=MIC STONE)
   ENTER "MIC STONE" INTO MAD GIVES NO ADDRESS

FERRY BUILDING
   NOTE MESSAGE ON RIGHT WALL

TAD TIMOV APARTMENT
   ENTER-AND DIE.SILLY SOD.DON`T BOTHER TO GO BACK

MANHUNTERS APARTMENT
   ENTER ROOM
   GET CLOTH FROM DRAWER (NOTE MESSAGE)

HYDE ST PIER
   NOTE ALCATRAZ
   LOOK AT CAGE
   GO DOWN STEPS LEFT
   LOOK UNDER PIER
   CLIMB POLE
   LOOK IN SEWER RIGHT
   DIE AS RAT FOOD

   THAT SHOULD END DAY 1.THE 2 VICTIMS WERE MIC STONE & TAD TIMOV

DAY 2
   TRY TO FOLLOW THE PLOT ON THE MAD MACHINE

   FOLLOW ALL TRACKS TO :-
.                        PIER 5
                         TEMPLE
                         SHOP
                         TRANSAMERICA PYRAMID
                         DR`S HOUSE
                         LAUNDRY
                         CABLECAR BARN
                         PRIVATE CLUB
PIER 5
   EXAMINE BODY
   TAKE MUZZLE
   USE FANG
   NOTE MISSING FINGER

TAD TIMOV APPARTMENT
   ENTER APPARTMENT
   USE MUZZLE IMMEDIATELY
   GET CAMERA
   STUDY PICTURE ON WALL LEFT (NOTE NAMES & PATTERNS)

TEMPLE
   ENTER MAIN DOOR
   GET SHIELD
   DEFEND YOURSELF (ARCADE GAME)
   ENTER STAIRWAY UNDER BUDDHA
   STUDY ALL STATUES,THEN....
   STUDY STATUES 3RD RIGHT FROM BOTTOM
                 1ST LEFT
                 4TH RIGHT
                  AND SUBSTITUTE NAMES IN DRAGON NOTE
   (THE CASTLE IS THE GATEWAY TO HELL)
   LOOK AT "HEAVEN STATUE"
   USE CLOTH
   (NOTE THE REBUS =F OAR   P INCHES  (ITS FOUR PINCHES IN CASE YOU HADN`T
   GUESSED))
   PROCEDE TO TOP OF STAIRS
   (ARCADE GAME - BRIDGE OVER ACID)
   WATCH
   WHEN CHALLENGED,GET SCROLL
   JUMP THROUGH WINDOW
   OUTSIDE,QUICKLY GO TO THE RIGHT
   ENTER NEW DOOR
   LOOK AT PIPE AND BOWLS
   TAKE 4 PINCHES FROM BOWL 2ND FROM LEFT
   SMOKE PIPE
   WATCH VISION CLOSELY
   TAKE STATUE
   LOOK AT SCROLL MESSAGE

SHOP
   ENTER
   WATCH
   LEAVE

TRANSAMERICA PYRAMID
   ENTER DOOR
   WATCH
   GET GUN ON RIGHT
   RE-ENTER AND GO FORWARD
   (ARCADE GAME)
   WATCH CLOSELY

DR`S HOUSE
   ENTER
   EXAMINE BODY
   ENTER BACKROOM
   LOOK AT BODY
   LOOK AT TEST TUBE
   USE FLASK
   GET LETTER FROM POCKET
   NOTE THE SIGNATURE ON THE LETTER...N GORING.COULD THIS BE NOAH G?
   OF COURSE IT IS.
   ENTER NOAH GORING INTO MAD AND GET ANOTHER LOCATION

CABLECAR BARN
   ENTER BARN
   ENTER DOOR LEFT FOR CABLECAR
   (ARCADE GAME)
   LOOK AT POSTERS
   LOOK AT BODIES
   GET LETTER

PRIVATE CLUB
   JUST TRY TO ENTER IT,THAT`S ALL...BUT TAKE NOTE OF THE HELPFUL MESSAGE
   ABOUT YOUR LOOKS,GIVEN AFTER YOU`VE BEEN REMOVED FROM YOUR SKIN...

SCIENTISTS HOUSE
   ENTER
   LOOK AT FILES IN CHRONOLOGICAL ORDER
   LOOK ON TABLE
   NOTE NEEDLE & THREAD
   GET MATCHES
   LOOK THROUGH WINDOW

WAX MUSEUM
   GO TO THE MUSEUM FRONT
   LOOK AT MAN
   USE MALLET
   INSIDE MUSEUM:-
   LOOK AROUND EVERYWHERE,RIGHT UP TO ZAC`S HOUSE
   THAT`S IT FOR TODAY

   TODAYS NAMES:-
   ZAC WEST,NOAH GORING

DAY 3
   THIS DAY MUST BE DONE IN THE BELOW ORDER

   FOLLOW ALL TRACKS TO
                      GHIRARDELLI SQUARE
                      WAX MUSEUM

LAUNDRY
   ENTER
   GO TO GIRL
   GIVE LAUNDRY TICKET
   FOLLOW GIRL WHEN ASKED
   WATCH-AND DON`T PANIC
   WAIT TO BE RESCUED
   BEFORE LEAVING ... GET WALKING STICK

GHIRARDELLI SQUARE (1ST TIME)
   GO TO ALLEY ENTRANCE
   GET RATS PAW
   CLIMB ROPE
   GO RIGHT TO SIGN
   (ARCADE GAME)
   USE WALKING STICK TO GET RING
   LEAVE SQUARE

SHOP
   ENTER SHOP
   USE RATS PAW
   PLAY GAME
   TAKE MASK WITH EYEHOLES

PRIVATE CLUB
   GO TO DOOR
   USE MASK
   KNOCK
   WATCH
   AS RAT PULLS OFF YOUR MASK:-
   USE FLASK
   GET HATCHET QUICK
   ESCAPE THROUGH DOOR RIGHT,FAST

WAX MUSEUM
   ENTER MUSEUM AS BEFORE (USE MALLET ETC)
   ENTER MIDDLE CHAMBER
   LOOK AT NEW BODY
   EXAMINE TIE
   USE FANG
   GET ORB CARD

GHIRARDELLI SQUARE (2ND TIME)
   GO TO TOP
   ENTER VENT/TUNNEL AT LEFT OF TOWER BLOCK
   AT GATE:-
   LOOK AT LOCK
   USE RING
   WATCH
   (WHEN YOU FALL AND PHIL LOSES HIS ARM QUICKLY....)
   GET ORB ON A STICK
   QUICKLY USE CAMERA
   USE FLASH
   ULTIMATELY YOU`LL END UP AT HYDE ST PIER

HYDE ST PIER
   GO DOWN STEPS
   LOOK UNDER PIER
   CLIMB POLE
   USE HATCHET
   WATCH

ALCATRAZ
   IN STORE ROOM:-
   USE HATCHET
   AT CAGES:-
   LOOK IN CAGES
   IDENTIFY `MING'
   USE STATUE
   GO LEFT TO CELL ACCESS MACHINE
   USE ORB CARD
   WHILE BEING SCANNED,USE ORB ON A STICK
   WATCH..
   AT BALOON:-
   LOOK AT BALOON
   LOOK AT HANDLE
   TURN HANDLE
   USE MATCHBOX TO LIGHT GAS JET
   WATCH..
   (ARCADE GAME)
   (YOU MUST STEER THE BALOON TO JULIUS`S CASTLE,2ND BUILDING DOWN FROM
   THE RIGHT HAND SIDE.)

IN HELL
   HERE YOU HAVE A PROBLEM TO SOLVE.REMEMBER THE MESSAGE `BRING US TO HELL
   AND WE`LL SHOW YOU FREEDOM'
   THERE ARE THREE BUTTONS,WHICH IDENTIFY THE LOCATION OF LAVA,ROBOTS AND
   SLAVES.THERE ARE A NUMBER OF `GATES'.FIRST,CLOSE ALL GATES.MOVE ROBOTS
   TO A CELL NEXT TO THE FIRST LAVA CELL.OPEN THE GATE TO SWAMP THE ROBOTS.
   PLOT THE LAVA ROUTE,TO DIRECT LAVA ONLY TO THE TOWERS AT THE TOP,THEN
   MOVE ALL SLAVES OUT OF IT`S WAY WITHOUT MOVING ANY SLAVES INTO OR OUT
   OF A NAMED CHAMBER.

End.
