Solucja do gry Skaut Kwatermaster

Stoisz przed rupieciarniä w PGR. Obok znajduje si samochód. Otwórz bagaznik i 
wyjmij srubokret. Udaj sie w lewo do tartaku. Wez siekiere. Idz dalej w lewo, az 
dotrzesz do bramy obozu, pod którä lezy lupa. Podnies jä. Za bramä znajduje sie 
plac apelowy. Na srodku stoi maszt flagowy, a na ziemi lezy talia kart. Wez karty, a 
nastepnie uzyj siekiery do przeciecia linki. Podniez patelnie, nie zapomni zabrac 
odcietej linki.
Idz przed dom soltysa i podnies srubokret krzyzowy lezäcy pod scianä. Odkrec nim 
tabliczke. Zlamie sie, wiec ponów próbe przy uzyciu srubokreta znalezionego w 
samochodzie. Nastepnie udaj sie do zamku. Wejdz do srodka. Na dziedzincu 
przeczytaj napis z tablicy (potrzebna bedzie lupa). Tekst jest pisany alfabetem 
Morse'a i brzmi: "Do rozbicia atomu pod bramä zamku przyda Ci si? mlotek 
origami, zrobiony z kartki papieru". Ze sciany zdejmij kolo ratunkowe. Idz do holu 
zamkowego. Zabierz rapier i magicznä ksiege. W drodze powrotnej zabierz z 
ogródka lopate oraz plachte. Przy grobowcu zatrzymaj sie, przeczytaj napis na 
tabliczce. Wejdz do krypty. Jest tam klapa w scianie. Otwórz jä i zamknij kilka razy, 
az wykrecisz srubke. Nastepnie za pomocä magicznej ksiegi wywolaj ducha i walnij 
go patelniä. Wypadnie mu szczeka, którä musisz zabrac. Wyjdz z krypty i udaj sie w 
prawo. Zamkni brame cmentarnä i uzyj na niej szczeki. Wez metalowy pret.
Gdy bedziesz z powrotem w centrum, udaj sie do sklepu. Zbierz nastepujäce 
przedmioty: ser, czerwonä farbe i niebieskä butelke. Wlóz karty do maszyny liczäcej 
pieniädze - znajdziesz karte plywackä. Teraz idz na pomost do faceta lowiäcego 
ryby. Pokaz mu karte p?ywackä. Gdy wpadnie do wody, rzuc kolo ratunkowe. 
Odchodzäc zabierz wedke. Wracajäc, napelnij niebieskä butelke wodä z kranu przy 
rupieciarni. Z napelnionä butelkä wejdz do domu soltysa, otwórz klape w lewym 
rogu i uzyj butelki. Po destylacji zanies napój do baru i daj go pijaczkom. W zamian 
dostaniesz pióropusz.
Idz teraz do jednostki wojskowej. Na ogrodzeniu napisz czerwonä farbä "Guns" i 
wejdz do budynku stojäcego w glebi. W srodku siedzi handlarz broniä i trzyma w 
reku granat. Uzyj wedki, zeby wyciägnac z niego zawleczke. Nastepnie pozbieraj 
nastepujäce przedmioty: karabin, odpady radioaktywne, maske gazowä, helm, 
radiostacje oraz kartke papieru (ta ostatnia nie przyda Ci sie, ale program podpowie, 
zeby? poszukac papieru kredowego - chodzi o plakat wiszäcy w rupieciarni).
Udaj si? do czolgu. Uzyj zlamanego srubokretu do wywolania awarii. Idz do latryny. 
Otworzysz jä rapierem. Ze srodka zabierz nuty, a nastepnie wejdz i uzyj radiostacji. 
Otrzymany przekaz stanowi wskazówke do dalszego dzialania.
Idz do lasu. Zerwij z krzaka jagody. Za pomocä plachty zdejmij z drzewa gniazdo os. 
Pójdz do soltysa, pogadaj z nim, a nastepnie uzyj gniazda os. Zadowolony soltys nie 
zauwazy, jak w chwile pózniej zlamiesz mu na glowie lopaty. Idz do kosciola i 
przeczytaj przez lupe napis na kamiennej tablicy. Napis glosi: "Turysta potrafi 
ugotowac z jagód eliksir skocznosci, przydatny na przystanku". Aby sporzädzic eliksir 
idz do kucharza siedzäcego za latrynä w namiocie. Pogadaj z nim i daj mu jagody. 
Po ugotowaniu eliksiru zabierz kociolek i idz na przystanek. Tam Otwórz klape od 
smietnika i wypyj eliksir. W ten sposób znajdziesz sie w mieszkaniu scenarzysty, 
gdzie lezy zarówka. Z zarówk? idz do tartaku. W szopie stojäcej w glebi zapal 
zarówke i wez tokarke. Z karabinu zrób flet. W tym celu wlóz go do maszynerii 
stojäcej przed szopä. Flet zabierz ze sobä, a tokarke zaniez do czolgu i wrzuz przez 
dziure zrobionä srubokretem. Teraz idz do latryny i uzyj sznurka, aby wyciägnäc ze 
srodka but. Wez go i uzyj na dystrybutorze 
Polo Cocty. Wypij zawartosc otrzymanej puszki. Dzieki nowo nabytej mocy wrzuc do 
lufy zlamany kij od lopaty. Idz do czolgu i wez wystruganego konika szachowego.
Teraz udaj sie do rupieciarni, wez plakat, zrób z niego mlotek. Nastepnie idz do 
zamku i tam uzyj mlotka origami do wysadzenia ogrodzenia. Wez oliwiarke lezäcä 
pod murem i wróc z niä do rupieciarni. Uzyj jej, wejdz na skrzynie, aby dosiegnäc 
butelki od smietany stojäcej na pólce, do lewej stronie. Idz teraz
przed bar i obejrzyj skrzynke pocztowä. Musisz wyslac mamie pamiätke z wakacji, w 
tym celu uzyj konika na butelce, a po wrzuceniu go do skrzynki idz na przystan. 
Zalóz maske gazowä dla upozorowania napadu i zdobycia pieniedzy. Z pieniedzmi 
pójdz do baru kupic piwo. Poniewaz harcerze nie moga pic, barman sam je wypije i 
wyrzuci butelke. Wez ja i idz do kosciola. Tam nabierz swieconej wody. Wychodzäc 
uzyj odpadów radioaktywnych na serze, a z napelnionä butelkä idz do domu 
soltysa. Przeprowadz kolejnä destylacje i zanies napój pijaczkom. W zamian dadzä Ci 
luk.
Pora odszukac kreta. Idz do lasu. Tam, gdzie znajdowaly sie osy, zagraj na flecie - 
pojawi sie mysz. Daj jej radioaktywnego sera, a przeistoczy sie w kreta. Poniewaz 
kret lubi robaki, wiec bedziesz musial jednego wykopac. Idz do bramy obozu i tam 
zlamanä lopatä wykop dzdownice. Wróc po kreta. Zanies go do grobowca. Tam uzyj 
wiadra na krecie, w wyniku otrzymasz kretobebenek. Idz teraz do lasu i porozmawiaj 
z drzewem. Aby je rozerwac przyczep mu tabliczke i zalóz pióropusz. Wywolasz 
piorun, który roztrzaska drzewo na kawalki. Jeden taki kawalek musisz zabrac. Idz z 
nim do namiotu i indin?skim sposobem rozpal ogien - uzyj luku na kawalku 
drewna. Nastepnie wez palnik acetylenowy i idz z nim do czolgu. Postukaj w niego 
metalowym pretem, a nastepnie zapal od zaru palnik i uwolnij z pulapki Luize.

  









