include ../../options.mk

PROGNAME = NickFaldosGolf


WHDLOADER = $(PROGNAME).slave
WHDLOADERCD = $(PROGNAME)CD32.slave
SOURCE = $(PROGNAME)HD.s
SOURCECD = $(PROGNAME)CD32HD.s

all :  $(WHDLOADER) $(WHDLOADERCD)

$(WHDLOADER) : $(SOURCE)
	$(WDATE)
	$(VASM) -o $(WHDLOADER) $(SOURCE)
$(WHDLOADERCD) : $(SOURCECD)
	$(WDATE)
	$(VASM) -o $(WHDLOADERCD) $(SOURCECD)
